title: Color Picker
description: Library for Android by vadiole
markdown: GFM
remote_theme: maxwellpollack/printy
site_favicon: https://raw.githubusercontent.com/vadiole/colorpicker/master/assets/favicon.png
